services:
  minecraft:
    build:
      context: .
      args:
        - "WORKDIR=/minecraft"
    image: bernardo1r/minecraft
    container_name: minecraft
    ports:
      - 25565:25565
    pull_policy: never
    tty: true
    restart: always
    environment:
      DOWNLOAD_URL: "https://piston-data.mojang.com/v1/objects/64bb6d763bed0a9f1d632ec347938594144943ed/server.jar"
      EULA: true
